name: App Delivery

on:
  push:
    branches:
      - base

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn isready

      - name: Delivery to Pinata
        uses: aquiladev/ipfs-action@v0.1.5
        id: pinata
        with:
          path: ./build
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          pinataPinName: ualeto-frontend

      - name: Update Cloudflare DNS
        uses: xorilog/cloudflare-dns-action@1.0.0
        id: cloudflare
        env:
          RECORD_DOMAIN: ualeto.app
          RECORD_TYPE: TXT
          RECORD_VALUE: dnslink=/ipfs/${{ steps.pinata.outputs.hash }}
          RECORD_NAME: _dnslink
          RECORD_TTL: 1
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}