name: App Delivery

on:
  push:
    branches:
      - base

jobs:
  build:
    name: Run build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn isready

      - name: Delivery to Pinata
        uses: aquiladev/ipfs-action@v0.1.5
        id: pinata
        with:
          path: ./build
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          pinataPinName: ualeto-frontend

      - name: Update Cloudflare DNS
        uses: wei/curl@v1.1.1
        id: cloudflare
        with:
          args: -X PUT 'https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/dns_records/${{ secrets.CLOUDFLARE_RECORD_ID }}' -H 'X-Auth-Email:${{ secrets.CLOUDFLARE_AUTH_EMAIL }}' -H 'X-Auth-Key:${{ secrets.CLOUDFLARE_AUTH_KEY }}' -H 'Content-Type:application/json' --data '{"type":"TXT","name":"_dnslink","content":"dnslink=/ipfs/${{ steps.pinata.outputs.hash }}","ttl":120,"proxied":false}'
